language: python
python:
  - "3.4"
install: 
  - pip install -r requirements.txt
  - pip install coveralls    
script:
  - python setup.py unittests
after_success:
  - ls _doc/sphinxdoc/source/*
  - coveralls --help
  - coveralls --verbose